message(STATUS "Adding bundled Google Benchmark")

set(BENCHMARK_ENABLE_TESTING OFF CACHE BOOL INTERNAL)
set(BENCHMARK_ENABLE_INSTALL OFF CACHE BOOL INTERNAL)
set(BENCHMARK_ENABLE_GTEST_TESTS OFF CACHE BOOL INTERNAL)

set(BENCHMARK_SRC_DIR ${CMAKE_CURRENT_LIST_DIR}/thirdparty/benchmark)
set(BENCHMARK_BIN_DIR ${CMAKE_BINARY_DIR}/_benchmark_build)

add_subdirectory(${BENCHMARK_SRC_DIR} ${BENCHMARK_BIN_DIR})
